const phrasesList: string[][] = [
    [
        "O calça apertada",
        "A ONU, um conluio de farsantes,",
        "Grande parte da imprensa",
        "Nosso \"imparcial\" STF",
        "PT, PSOL e PC do B",
        "A imprensa vermelha",
        "Os líderes da \"nova ordem mundial\"",
        "A Casa Legislativa",
        "Todo mundo",
        "Esse cartunista engraçalóide",
        "O Emanuel Lacrón",
        "O herói da esquerda caviar",
        "Pra variar, o Felipe Feto",
        "Mais uma vez a Globolixo",
        "Não me surpreende a Folha",
        "Esse tal de Henry Bragalho",
        "Esse desesperado por tetas estatais",
        "A quadrilha (vulgo, organização terrorista) chamada MST",
        "Esse tucanista isentão vagabundo",
        "A lacrosfera",
        "O sistema corrupto",
    ],
    [
        "que concomitantemente ataca o estado democrático de direito",
        "que em tempo nenhum deixou meu pai labutar em serenidade",
        "que sempre dilapida nosso fleumático governo",
        "que defende a idiossincrasia que vigora nos últimos tempos",
        "mais uma vez permuta atenção sem pudor algum",
        "demonstrou toda sua sumidade",
        "encarecidamente desferiu golpes na honra do Brasil",
        "uniu forças com a bandidagem",
        "conhecido pela sua imbecilidade eflúvia",
        "já trabalha incessantemente para apequenar nossa prole",
        "juntou o pior do pensamento esquerdista ao esgoto da nação",
        "só diz palavras ensaiadas",
        "mantém o modus operandi dessa raça de crápulas",
        "quer se pagar de \"curnalista\"",
        "quer atacar de PHD em pecúlio",
        "que já figurou nas páginas pelos seus rompantes abjetos",
        "sempre aludiu a uma ideia identitária absurda",
        "que tanto atenta contra a meritocracia pujante",
        "sempre se diz pacifista, mas que de paz não entende nada",
        "se diz moralmente superior mas não atua de forma coerente",
        "doravante se execra da responsabilidade",
    ],
    [
        "ao atacar meu pai covardemente",
        "ao bravejar aos sete ventos sua procedência",
        "ao famigerar aspargos comentários sobre os militares",
        "defendeu mais uma vez a chucra ditadura cubana",
        "falaciou contra o homem de bem",
        "e agora festeja sobre a desgraça do leão do monte",
        "fazendo pouco de um assunto pertinente",
        "torce contra os avanços institucionais libertários",
        "quando faz jus ao status de absurdistas",
        "para rodar o moinho em torno do eixo democrático",
        "deixando claro, novamente, as intenções de dominação mental",
        "cai no sensacionalismo barato e retórico paulatinamente",
        "usurpando a narrativa do debate público",
        "sacramentou a loucura que esse povo vive,",
        "pagou pela boca a sua palestra",
        "jogou abertamente como uma cobra",
        "sistematicamente defeca no eleitorado",
        "não consegue refletir e sequer reconhecer sua ignorância",
        "se mostra desesperado por um pouco de palanque",
        "defendeu com unhas e dentes a \"ciência\"",
        "sem perder a pose de semideus",
    ],
    [
        "exatamente como George Soros deseja",
        "aos moldes Trotskistas clássicos",
        "e ainda me chama de \"cabeça de caixa d'água\"",
        "aos moldes Trotskistas clássicos",
        "dá a entender que começa a eclodir uma panaceia",
        "só para defender seus próprios interesses",
        "militando, militando e militando",
        "fazendo um desserviço ao Brasil e ao brasileiro",
        "provando que de compreensivos eles não têm nada",
        "fecundando uma ideia absurda na mente dos jovens",
        "validando o discurso golpista de sempre",
        "mostrando a paródia que esse povo é",
        "pleiteando seu lugar de farsa nos anais da história",
        "cerceando liberdades recém conquistadas",
        "fabricando loucuras a seu bel prazer",
        "prostituindo nossa tão abalada economia",
        "em nome da dominação cultural",
        "saudosamente lembrando da época petralhista",
        "esfolando a soberania do globalismo",
        "pautando ideias que a biologia já refutou",
        "ignorando a vontade popular, pra variar",
    ]
]

export default phrasesList